from .test_docker import *


FEATURES['ENABLE_SERVICE_STATUS'] = False
FEATURES['ENABLE_SHOPPING_CART'] = False
FEATURES['ENABLE_VERIFIED_CERTIFICATES'] = False
FEATURES['ENABLE_GRADE_DOWNLOADS'] = False
FEATURES['ALLOW_COURSE_STAFF_GRADE_DOWNLOADS'] = False
FEATURES['EMBARGO'] = False
FEATURES['ENABLE_COMBINED_LOGIN_REGISTRATION'] = False
FEATURES['MILESTONES_APP'] = False
FEATURES['ENABLE_ENROLLMENT_TRACK_USER_PARTITION'] = False
FEATURES['ENABLE_EDXNOTES'] = False
FEATURES['ENABLE_TEAMS'] = False
FEATURES['ENABLE_COURSEWARE_SEARCH'] = False
FEATURES['ENABLE_DASHBOARD_SEARCH'] = False
FEATURES['ORGANIZATIONS_APP'] = False
FEATURES['ENABLE_FINANCIAL_ASSISTANCE_FORM'] = False

ED2GO_API_KEY = 'dummy-api-key'
ED2GO_REGISTRATION_SERVICE_URL = 'www.example.com'
